identifier: l5tda8r9lfl1r13d
appPort: 30007
staticPort: 30008
reloadPort: 2667
hostName: localhost
projectName: victor-odukoya
homeFolder: >-
  C:\Users\Victo\OneDrive\Dokumente\GitHub\VictorOdukoya.github.io\victor-odukoya
distFolder: ./dist/victor-odukoya
outDir: >-
  C:\Users\Victo\OneDrive\Dokumente\GitHub\VictorOdukoya.github.io\victor-odukoya\dist\static
handle404: ''
allowErrorCollect: false
